# This is autogenerated config
# See the documentation for more details
# https://docs.scalr.com/en/latest/blob_migration

mysql: ${db_user}:${db_pass}@tcp(${db_host}:${db_port})/${db_name}
crypto_key: ${crypto_key}
google_cloud_storage:
  bucket: ${bucket_id}
